version: '3.7'

services:
  app:
    container_name: bank_transactions_frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development